#!/bin/bash
#
# Create Pokemon.md with lookup names
#

POKEMON_DATA_URL='https://raw.githubusercontent.com/RyanMillerC/poke-position-images/master/pokemon-data.json'

echo 'Downloading pokemon-data.json...'
curl -s "${POKEMON_DATA_URL}" -o pokemon-data.json

echo 'Creating docs/pokemon.md...'
cat > docs/pokemon.md <<EOF
<!-- This file is generated by ./scripts/create_pokemon_md.sh. DO NOT EDIT IT DIRECTLY -->

# Pokémon Images

This page contains images and lookup names for each Pokémon. Because some Pokémon
have unique names with special characters, it's a good idea to validate the name
using this list if you run into issues setting poke-line to a particular value.

## Pokémon List

| Pokédex ID | Pokémon Name | Sprite |
| ---------- | ------------ | ------ |
EOF

get_pokemon_data() {
    index="${1}"
    pokemon_id=$(jq -r ".[${index}].id" pokemon-data.json)
    pokemon_name=$(jq -r ".[${index}].name" pokemon-data.json)
    pokemon_type=$(jq -r ".[${index}].type" pokemon-data.json)
    pokemon_image_file_name=$(echo "${pokemon_name}" | sed 's/ /\&#32;/')
    printf "| #${pokemon_id} | \`${pokemon_name}\` | ![${pokemon_name}](/img/pokemon/${pokemon_image_file_name}.png)"
    for ((element_counter=0; element_counter<10; element_counter++)) ; do
      printf "![-](/img/elements/${pokemon_type}.png)"
    done
    echo " |"
}

echo 'Adding data to Pokemon.md...'
number_of_pokemon=$(jq '. | length' pokemon-data.json)
for ((iterator=0; iterator<number_of_pokemon; iterator++)) ; do
    echo "Processing Pokemon $((iterator+1)) of $((number_of_pokemon))..."
    get_pokemon_data "${iterator}" >> Pokemon.md
done
echo '' >> Pokemon.md

echo 'Complete!'
