#!/bin/bash
#
# Create Pokemon.md with lookup names
#

POKEMON_DATA_URL='https://raw.githubusercontent.com/RyanMillerC/poke-position-images/master/pokemon-data.json'

echo 'Downloading pokemon-data.json...'
curl -s "${POKEMON_DATA_URL}" -o pokemon-data.json

echo 'Creating docs/pokemon.md...'
cat > docs/pokemon.md <<EOF
<!-- This file is generated by ./scripts/create_pokemon_md.sh. DO NOT EDIT IT DIRECTLY -->

# Pokémon Images

This page contains images and lookup names for each Pokémon. Because some Pokémon
have unique names with special characters, it's a good idea to validate the name
using this list if you run into issues setting poke-line to a particular value.

## Pokémon List

<table>
  <tr>
    <th width="50">Pokédex ID</td>
    <th width="150">Pokémon Name</td>
    <th width="150">Sprite</td>
  </tr>
EOF

get_pokemon_data() {
    index="${1}"
    pokemon_id=$(jq -r ".[${index}].id" pokemon-data.json)
    pokemon_name=$(jq -r ".[${index}].name" pokemon-data.json)
    pokemon_type=$(jq -r ".[${index}].type" pokemon-data.json)
    pokemon_image_file_name=$(echo "${pokemon_name}" | sed 's/ /\&#32;/')
    echo "  <tr>"
    echo "    <td align=\"center\">${pokemon_id}</td>"
    echo "    <td><code>${pokemon_name}</code></td>"
    printf "    <td align=\"center\"><img src=\"/img/pokemon/${pokemon_image_file_name}.png\" alt=\"${pokemon_name}\" />"
    for ((element_counter=0; element_counter<10; element_counter++)) ; do
      printf "<img src=\"/img/elements/${pokemon_type}.png\" alt=\"-\" />"
    done
    echo "</td>"
    echo "  </tr>"
}

echo 'Adding data to Pokemon.md...'
number_of_pokemon=$(jq '. | length' pokemon-data.json)
for ((iterator=0; iterator<number_of_pokemon; iterator++)) ; do
    echo "Processing Pokemon $((iterator+1)) of $((number_of_pokemon))..."
    get_pokemon_data "${iterator}" >> docs/pokemon.md
done
echo '</table>' >> docs/pokemon.md

echo 'Complete!'
